pip3 install Django;
pip3 install djangorestframework;
pip3 install django-cors-headers;
pip3 install django-health-check;
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash;
nvm ls;
nvm install node;
nvm use node;
cd methdealer;
npm i;
