# Generated by Django 3.0.3 on 2020-02-07 08:39

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='equation',
        ),
        migrations.AddField(
            model_name='calculator',
            name='difficulty',
            field=models.TextField(default='e', validators=[calculator.models.validate_difficulty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='formula',
            field=models.TextField(default='x', validators=[calculator.models.validate_difficulty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='topic',
            field=models.TextField(default='numbers', validators=[calculator.models.validate_difficulty]),
            preserve_default=False,
        ),
    ]
