# Generated by Django 3.0.3 on 2020-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='simplify_formula',
            field=models.TextField(default='_'),
            preserve_default=False,
        ),
    ]
