# Generated by Django 3.0.3 on 2020-02-09 10:07

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200207_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='title',
            field=models.TextField(default='test', validators=[calculator.models.validate_empty]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='formula',
            field=models.TextField(validators=[calculator.models.validate_empty]),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='topic',
            field=models.TextField(validators=[calculator.models.validate_empty]),
        ),
    ]
