# Generated by Django 3.0.3 on 2020-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculator_simplify_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='calculation_formula_var_mapping',
            field=models.TextField(default='_'),
            preserve_default=False,
        ),
    ]
