# Generated by Django 3.0.3 on 2020-02-14 13:52

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200209_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='description',
            field=models.TextField(default='', validators=[calculator.models.validate_empty]),
            preserve_default=False,
        ),
    ]
