# Generated by Django 3.0.3 on 2020-03-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_calculator_graph_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='resource_links',
            field=models.TextField(default='_'),
            preserve_default=False,
        ),
    ]
