# Generated by Django 3.0.3 on 2020-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_calculator_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='legend',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
