# Generated by Django 3.0.3 on 2020-03-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_calculator_resource_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='expand_formula',
            field=models.TextField(default='_'),
            preserve_default=False,
        ),
    ]
