# Generated by Django 3.0.3 on 2020-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_calculator_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='alternative',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
