# Generated by Django 3.0.3 on 2020-02-17 15:23

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20200217_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='calculation_formula',
            field=models.TextField(default='', validators=[calculator.models.validate_c_formula]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='calculation_vars',
            field=models.TextField(validators=[calculator.models.validate_c_var]),
        ),
    ]
