# Generated by Django 3.0.3 on 2020-02-20 02:21

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20200217_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='calculated_units',
            field=models.TextField(default='', validators=[calculator.models.validate_empty]),
            preserve_default=False,
        ),
    ]
